### ISSUE TITLE
L'interface graphique est redessinée bien plus que nécessaire 

### ISSUE THREAD

**Issue by ComicScrip** [swietrc/xflood#6]
Cela ralentit énormément le jeu puisque l'interface est redessinée à chaque mouvement de souris. Pour résoudre le problème je propose d'enlever le renderClear à chaque tour de la boucle principale et de donner aux modules la responsabilité de faire ça uniquement lorsque c'est nécessaire.

**Comment by swietrc** [comment]
Fixed
